site_name: Evaluating AI Agents
site_description: "Evaluating AI Agents"

repo_url: https://evaluating-ai-agents.netlify.app/
repo_name: evaluating-ai-agents

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material" # readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "pink"
      accent: "grey"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "pink"
      accent: "white"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/Python-Test-Engineer/"

plugins:
  - search
  - mkdocstrings
  # - blog:
  #     blog_dir: blog
  #     blog_toc: true
  #     archive: true
  #     archive_name: All Articles
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Page tree
nav:
  - "About": "index.md"
  - "Talks": "talks.md"
  - "Current Concepts": "current_concepts.md"
  - "Evaluation":
      - "Overview": "evaluation/overview.md"
      - "LLM as Judge": "evaluation/rate_with_llm.md"
      - "Domain Expert": "evaluation/domain_expert.md"
      - "Refine": "evaluation/refine.md"
  - "Other Books":
      - "PyTest Cookbook": "books.md"
      - "PyTest Django Full Stack": "books.md"
  - "About Craig":
      - "Services": "craig/services.md"
      - "CV": "craig/cv.md"
      - "Courses": "craig/courses.md"
      - "Contact": "craig/contact.md"

copyright: |
  &copy; 2025 <a href="https://evaluating-ai-agents.netlify.app/"  target="_blank" rel="noopener">Craig West -  Evaluating AI Agents</a>
